### ISSUE TITLE
로그인 화면 버튼 2개 위치 & 크기

### ISSUE THREAD

**Issue by ZZANZU** [ZZANZU/android-server-hapdong#2]
이상해

**Comment by rightonbright** [comment]
수정했습니다!!
<img width="1680" alt="2018-06-01 10 28 21" src="https://user-images.githubusercontent.com/39338536/40843234-48ad8378-65eb-11e8-89ce-1eb3bc4d79b0.png">
<img width="499" alt="2018-06-01 10 31 06" src="https://user-images.githubusercontent.com/39338536/40843312-801cb5ae-65eb-11e8-8779-e0c63a201e0f.png">
